### ISSUE TITLE
What is the purpose of 'VideoCameraStreamer::kImageWidth' ?

### ISSUE THREAD

**Issue by sysu17364029** [cgsaxner/HoloLens2-Unity-ResearchModeStreamer#6]
Hi @cgsaxner ! Thank you so much for your project!
I think `‘VideoCameraStreamer::kImageWidth’` can modify the width of the frames and can make the size (bytes) of the frames smaller. I changed its value from 640 to 416, and added `print(image_size_bytes)` in 'hololens2_simpleclient.py' to see the size of received frames. But I found that the printed `'image_size_bytes'` were the same. I wonder what's the purpose of 'VideoCameraStreamer::kImageWidth' , or how could I resize and compress the frames?

**Comment by cgsaxner** [comment]
Hi @sysu17364029!
Yes you are right, with `kImageWidth` you can adjust the video frame size you are receiving, but only to some extend. The HoloLens 2 video camera offers several profiles and resolutions, which you can find [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/locatable-camera).

In the VideoCameraStreamer, we grab all video conferencing profiles, and then select the desired profile based on the width (640 px in this case). Since there is no profile with a width of 416, it apparently falls back to the 640x360 profile. If you want to grab smaller frames, you could try a width of 500 or 424 px instead. Note that setting `DBG_ENABLE_VERBOSE_LOGGING` to 1 should also print all available profiles on startup of the VideoCameraStreamer. 

In the `VideoCameraStreamer::SendFrame`, I've also included a parameter `scaleFactor`, which should allow you to downscale the frames by an integer factor, e.g. 2  to half the frame size by just skipping every second pixel. However, if you specifically need a frame width of 416, you would have to implement the scaling yourself using some kind of interpolation. 

Hope this could help!

**Comment by sysu17364029** [comment]
Hi @cgsaxner ~Your answer is very clear, which has helped me a lot. However, when I set the value of the parameter `scaleFactor` to 2， my `image_size_bytes` remains unchanged. Since `image_size_bytes = header.ImageHeight * header.RowStride` , I guess it is because `ImageHeight` and `RowStride` will not change according to the value of `scaleFactor`. 
In addition，when I set the value of `kImageWidth` to 424, my `header.ImageHeight`  is still 360, which is compatible with the width of 640. I'm confused. I wonder if there's anything else I haven't set up.

**Comment by cgsaxner** [comment]
Hello @sysu17364029,
you are absolutely right, I did not follow through with implementing the `scaleFactor`, sorry for that. The latest commit should fix this issue and scaling is working for me as expected now.

As for the problem with the wrong height after setting `kImageWidth` to 424, I unfortunately cannot reproduce it. When I set this parameter, I correctly receive frames of shape (240x424x3) with the client. Could you verify that the desired profile is found on the HoloLens, by setting `DBG_ENABLE_VERBOSE_LOGGING` to 1 in the VideoCameraStreamer.cpp? You should be getting an output like this:
![image](https://user-images.githubusercontent.com/29651139/114402523-3325f700-9ba4-11eb-8ee1-bb6f955a7ec6.png)

**Comment by sysu17364029** [comment]
Hi @cgsaxner !  Your code is working well!!!
At first I found that whatever I changed( `kImageWidth`, `scaleFactor`, even `DEG_ENABLE_BERBOSE_LOGGING` ), my output has not change at all, I was really frustrated. I firmly believe that there is no problem with the code, so I checked the setting of Unity. I suddenly found out that unity had a warning: "Setting 'Assets/Plugins/WSAPlayer/ARM64/HL2RmStreamUnityPlugin.dll' CPU value to X86". I set the CPU value back to ARM64, and everything went well.
Thank you so much, @cgsaxner !!!
